graph LR;

This["This"];
is["is"];
This --> is;
i1["imagination"];
is ==> i1;
o1["or"];
i1 --> o1;
r1["reality"];
o1 --> r1;
r2["reality"];
is ==> r2;
o2["or"];
r2 --> o2;
i2["imagination"];
o2 --> i2;
i1 ==>i2;
r1 .->r2;
