graph LR;

This[This];
Is[is];
This --> Is;
i1[imagination];
Is ==> i1;
o1[or];
i1 --> o1;
r1[reality];
o1 --> r1;
r2[reality];
Is ==> r2;
o2[or];
r2 --> o2;
i2[imagination];
o2 --> i2;
i1 .->i2;
r1 .->r2;
