graph RL;

Company["Company"];
Company_id["id"];
Company --> Company_id;
Company_id_city["id_city"];
Company --> Company_id_city;
_z8p6vq17g["name"];
Company --> _z8p6vq17g;
Department["Department"];
Department_id["id"];
Department --> Department_id;
Department_id_city["id_city"];
Department --> Department_id_city;
Department_id_boss["id_boss"];
Department --> Department_id_boss;
_wii9vme4h["name"];
Department --> _wii9vme4h;
Employee["Employee"];
Employee_id["id"];
Employee --> Employee_id;
Employee_id_city["id_city"];
Employee --> Employee_id_city;
_r6zra5o63["name"];
Employee --> _r6zra5o63;
City["City"];
City_id["id"];
City --> City_id;
State_id["id_state"];
City --> State_id;
_26hcdhsy6["name"];
City --> _26hcdhsy6;
State["State"];
State_id["id"];
State --> State_id;
Country_id["id_country"];
State --> Country_id;
_gzv6q2stb["name"];
State --> _gzv6q2stb;
Country["Country"];
Country_id["id"];
Country --> Country_id;
_ws52jkggz["name"];
Country --> _ws52jkggz;
Department_id_boss .->Employee_id;
Company_id_city .->City_id;
Department_id_city .->City_id;
Employee_id_city .->City_id;
