graph TD;

Company["Company"];
Company_id["id"];
Company --> Company_id;
Company_id_city["id_city"];
Company --> Company_id_city;
_wa1k45373["name"];
Company --> _wa1k45373;
Department["Department"];
Department_id["id"];
Department --> Department_id;
Department_id_city["id_city"];
Department --> Department_id_city;
Department_id_boss["id_boss"];
Department --> Department_id_boss;
_n0xfmkrwb["name"];
Department --> _n0xfmkrwb;
Employee["Employee"];
Employee_id["id"];
Employee --> Employee_id;
Employee_id_city["id_city"];
Employee --> Employee_id_city;
_62u8sr7ae["name"];
Employee --> _62u8sr7ae;
City["City"];
City_id["id"];
City --> City_id;
State_id["id_state"];
City --> State_id;
_v8oe8bx2b["name"];
City --> _v8oe8bx2b;
State["State"];
State_id["id"];
State --> State_id;
Country_id["id_country"];
State --> Country_id;
_pdkhzfgsh["name"];
State --> _pdkhzfgsh;
Country["Country"];
Country_id["id"];
Country --> Country_id;
_3ls227l2p["name"];
Country --> _3ls227l2p;
Department_id_boss .->Employee_id;
Company_id_city .->City_id;
Department_id_city .->City_id;
Employee_id_city .->City_id;
