graph TD;

Company["Company"];
Company_id["id"];
Company --> Company_id;
Company_id_city["id_city"];
Company --> Company_id_city;
_gcss73w8q["name"];
Company --> _gcss73w8q;
Department["Department"];
Department_id["id"];
Department --> Department_id;
Department_id_city["id_city"];
Department --> Department_id_city;
Department_id_boss["id_boss"];
Department --> Department_id_boss;
_xj1fpvhdl["name"];
Department --> _xj1fpvhdl;
Employee["Employee"];
Employee_id["id"];
Employee --> Employee_id;
Employee_id_city["id_city"];
Employee --> Employee_id_city;
_lmzlfuyo5["name"];
Employee --> _lmzlfuyo5;
City["City"];
City_id["id"];
City --> City_id;
State_id["id_state"];
City --> State_id;
_s9aqqh8t9["name"];
City --> _s9aqqh8t9;
State["State"];
State_id["id"];
State --> State_id;
Country_id["id_country"];
State --> Country_id;
_r667vrwy5["name"];
State --> _r667vrwy5;
Country["Country"];
Country_id["id"];
Country --> Country_id;
_sa3pbns9c["name"];
Country --> _sa3pbns9c;
Department_id_boss .->Employee_id;
Company_id_city .->City_id;
Department_id_city .->City_id;
Employee_id_city .->City_id;
