graph LR;

Inicio["Inicio"];
Programas["Programas"];
Inicio --> Programas;
De_hacking["De hacking"];
Programas --> De_hacking;
De_bases_de_datos["De bases de datos"];
Programas --> De_bases_de_datos;
De_noseque["De nosequé"];
Programas --> De_noseque;
